[package]
name = "cifar10"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "*", features = ["train", "candle"]}
image = "0.25.6"
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde = { version = "1.0.219", features = ["derive"] }
